app:
  name: "wep_app"
  mode: "dev"
  port: 8081
  start_time: "2021-01-01"
  machine_id: 1

log:
  level: "debug"
  filename: "wep_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 13306
  user: "root"
  passwork: "root1234"
  dbname: "sql_demo"
  max_open_conns: 20
  max_idle_conns: 10

redis:
  host: "127.0.0.1"
  port: 16379
  password: ""
  db: 0
  pool_size: 100